export { default as Navigation } from "./Navigation";
export { default as Footer } from "./Footer";
export { default as Home } from "./Home";
export { default as Ticket} from "./Ticket";
export { default as About } from "./About";
export { default as Blog } from "./Blog";
export { default as Nautika } from "./Nautika";
export { default as Sealink } from "./Sealink";
export { default as Explore } from "./Explore";
export { default as Contact } from "./Contact";